---
- name: Test basic auth for Uri module
  uri:
    url: https://127.0.0.1:10443/api/diagnostics/firewall/log
    method: GET
    url_username: "{{api_key}}"
    url_password: "{{api_secret}}"
    force_basic_auth: yes
    validate_certs: no
    return_content: no
  register: basic

- name: debug
  debug:
    var: basic
