---
# Overwrite config and reload needed services
- name: Write config
  copy:
    src: config.xml
    dest: /conf/config.xml
    owner: root
    group: wheel
    mode: 0644
    backup: yes
  register: config

- name: Reload services and webgui
  command: "{{ item }}"
  with_items:
      - configctl service reload all
      - configctl webgui restart
  when: config.changed
